#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
nm-applet &
pgrep -x volumeicon || volumeicon &
picom &
wal -i $HOME/Wallpapers/5.jpg

bspc monitor -d I II III IV V VI

bspc config border_width         3
bspc config window_gap          14

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config focus_follows_pointer true
bspc config gapless_monocle       true
bspc config focus_by_distance	  true
bspc config history_aware_focus   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Import colors from Pywal
. "${HOME}/.cache/wal/colors.sh"

# border colors
bspc config normal_border_color "$color8"
bspc config active_border_color "$color4"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color8"

